### PR TITLE
refactoring for controllers

### PR DESCRIPTION
**Pull request by suadev**
- Added dotnet core api convention feature
- Cleaned some redundant things

### CODE REVIEW

**Comment by kgrzybek** [comment]
Hi Suat,

Thanks for PR. I think dotnet core api convention feature is useful, but I am not for adapting the action methods names to match conventions. I would prefer opposite - adapt the conventions to match the names of action methods. 

I like clear, well-descriptive naming on all levels of application. Names like "Get", "Put", "Post" mean nothing to me. 

What do you think?

**Comment by suadev** [comment]
Hi,

You are welcome :) 

If i have a controller called "CustomerController", the Post method means `Create a customer for me` and Put means 'Update this customer'.  Right? Of course you can name it as 'CreateCustomer' DefaultApiConvention handles Post and Create prefixes.  Check this out please: 
 https://raw.githubusercontent.com/aspnet/Mvc/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/DefaultApiConventions.cs

But if you want to use RegisterCustomer, it's ok. You can write you own apiconvention that derives from DefaultApiConvention. So 'Register' prefix will be handle as Post action. 
https://devblogs.microsoft.com/aspnet/asp-net-core-2-20-preview1-open-api-analyzers-conventions/

Otherwise, You will have to add 'ProducesResponseType' attribute your all action methods. If that's okay for you, i remind that; "The code that's easiest to maintain is code that was never written."

Also you don't need to use [FromBody] and [FromRoute] attributes when you use [ApiController] attribute on top of you controller.

**Comment by kgrzybek** [comment]
> If i have a controller called "CustomerController", the Post method means Create a customer for me and Put means 'Update this customer'. Right?

You know this only because you know how to design REST API. I would rather stick to DDD Ubiquitous Language and name methods and other members using language understandable by all people including business people even on GUI/Controller layer. Common language should be used literally everywhere, not only in Domain Model.

> But if you want to use RegisterCustomer, it's ok. You can write you own apiconvention that derives from DefaultApiConvention. So 'Register' prefix will be handle as Post action.

Yes, as I wrote above :) I would rather create own apiconvention to support my language.

> "The code that's easiest to maintain is code that was never written."

"It depends". Sometimes coding by conventions causes a lot of "magic" and I think it should be used with caution. In this scenario I agree - it is good.

>Also you don't need to use [FromBody] and [FromRoute] attributes when you use [ApiController] attribute on top of your controller.

I agree

**Comment by suadev** [comment]
Done.

**Comment by suadev** [comment]
I was changing my wrong commit email address to correct one, so i made --force push. I forgot this pull request will be affected this force push. Therefore github bot closed the PR 😮

**Pull request closed without merging**
